#!/bin/bash -eux

mkdir -p ./conf/root
chmod -R  700 ./conf

PASSPHRASE=`tr -dc A-Za-z0-9_ < /dev/urandom | head -c 20 | xargs`
echo "PASSPHRASE=${PASSPHRASE}" > ./env

echo "We advise you to backup this PASSPHRASE in a safe place"

echo "configuring ssh..."
mkdir ./conf/ssh
ssh-keygen -f ./conf/ssh/id_rsa -N '' -t rsa
